package uk.gov.moj.cpp.prosecution.casefile.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.prosecution.casefile.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for initiating a CC prosecution"
  when
    $outcome: Outcome();
    $action: Action(name == "prosecutioncasefile.command.initiate-cc-prosecution");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getInitiateCCProsecutionGroups()))
    || eval(userAndGroupProvider.hasPermission($action, RuleConstants.expectedPermissionsForCase()));
  then
    $outcome.setSuccess(true);
end
