package uk.gov.moj.cpp.prosecution.casefile.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.prosecution.casefile.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Add Material"
  when
    $outcome: Outcome();
    $action: Action(name == "prosecutioncasefile.add-material");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddMaterialActionGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Add Materials"
  when
    $outcome: Outcome();
    $action: Action(name == "prosecutioncasefile.add-materials");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddMaterialActionGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Add Material for Case Defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "prosecutioncasefile.add-material-v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddMaterialActionGroups()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Add Material for Application Defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "prosecutioncasefile.add-application-material-v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getAddMaterialActionGroups()));
  then
    $outcome.setSuccess(true);
end